// APIs
// POST /api/todos
// Body is in JSON with fields: text
// id is autogenerated, done is false by default

// UPDATE /api/todos/{id}
// Body is in JSON with fields: text (optional), done (optional)
// optional = ignore if empty

// DELETE /api/todos/{id}

// GET /api/todos

// ToDo Data Model
// id (unique) : integer
// text : string
// done : boolean
var express = require('express')
var app = express()

app.use(express.json())

var data = {}

app.get('/api/todos', function(req, res){
    res.send(data)
})

app.post('/api/todos', function(req, res){
    const text = req.body.text
    if(text == ''){
        res.status(400).send('Error : text is empty')
    }
    const id = Math.floor((Math.random() * 100) +1) // generate 1 - 100
    data[id] = {
        text: text,
        done: false
    }

    res.send('todo added')
})

app.put('/api/todos/:id', function (req, res){
    const id = req.params.id;
    if (id in data) {
        if (req.body.done == undefined||req.body.done == '') {
            data[id].done = req.body.done;
        }
        const text = req.body.text;
        const done = req.body.done;

        data[id] = {
            text: text,
            done: done,
        };

        res.send('data updated');
        return;
    }
    res.status(400).send('error');
});

app.delete('/api/todos/:id', function(req, res){
    const id = req.params.id
    if (id in data){

    
    delete data[id]
    res.send('data deleted')

    }else {
        res. status(400).send('ID ngak sama')
    }
    
})

app.listen(5000, ()=>{
    console.log('server running')
})